#!/bin/bash

# spot++ for SBS 

currentdir=$PWD

exp=$EXPERIMENT
echo "exp = $exp"

fileprefix=prexLHRS
# prexLHRS

case $1 in 
"" | "last")
    runnum=`cat ~adaq/datafile/rcRunNumberL`
    CFILE=/adaq1/data1/${fileprefix}_$runnum.dat.0
    if [ ! -f $CFILE ]
    then
	echo "ERROR: no CODA files"
	exit
    fi
    
    if [ -s $CFILE ] 
    then
	echo "opening $CFILE"
    else
        echo "ERROR: $CFILE does not exist or is empty"
        exit
    fi
        
    if [ -z $2 ]
    then
      FIRST=1
      LAST=50000
    else
	if [ -z $3 ]
            then
              FIRST=1
              LAST=$2
            else
              FIRST=$2
              LAST=$3
        fi
    fi    
    ;;
"help" | "HELP" )
    echo "Usage:"
    echo "raster++ "
    echo "->   standard plots from the last coda run"
    echo "raster++ help "
    echo "->   prints this message"
    echo "raster++ #### "
    echo "->   standard plots from run ####"
    echo "raster++ last #1 #2 "
    echo "->   plots from last coda run, using events from #1 to #2"
    echo "raster++ #### #1 #2 "
    echo "->   plots from coda run ####, using events from #1 to #2"
    echo "in all cases a new root file is generated, overwriting "
    echo "the previous one."
    echo "please communicate comments to reitz@jlab.org"
    echo " "
    exit;;
* )

    runnum=$1
# a trick for testing
     CFILE=/adaq1/work1/adaq/${fileprefix}_$1.dat.0
#    CFILE=/adaq1/data1/${fileprefix}_$1.dat.0
    if [ ! -f $CFILE ]
    then
       echo "ERROR: no CODA files"
       exit
    fi

    if [ -s $CFILE ] 
    then
	echo "opening $CFILE"
    else
        echo "ERROR: $CFILE does not exist or is empty"
        exit
    fi

    if [ -z $2 ]
    then
      FIRST=1
      LAST=50000
    else
	if [ -z $3 ]
            then
              FIRST=1
              LAST=$2
            else
              FIRST=$2
              LAST=$3
        fi
    fi    
    ;;   

esac

# cd /adaqfs/home/a-onl/rastersize/LeftHRS

# location of my rastersize_L.C script 
RASTER_PATH=$HOME/halla_online_beam_check/raster
cd $RASTER_PATH

echo "Current directory: $PWD"

# export DB_DIR=../DB
export DB_DIR=/adaqfs/home/a-onl/rastersize/DB
echo "DB_DIR = $DB_DIR"

#rm -f rastersize.root

ANALYZER_PATH=$HOME/dflay/ANALYZER/install

echo "ORIGINAL PATHS:"
echo "PATH = $PATH" 
echo "LD_LIBRARY_PATH = $LD_LIBRARY_PATH"

# use current ROOT, chosen analyzer
# udpate LD_LIBRARY_PATH 
export LD_LIBRARY_PATH=/adaqfs/coda/2.2/Linux/lib 
export LD_LIBRARY_PATH=/adaqfs/home/a-onl/evio-4.3/Linux-x86_64/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/adaqfs/home/a-onl/happexsp/TreeSearch:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/adaqfs/apps/ROOT/pro/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$ANALYZER_PATH/lib64:$LD_LIBRARY_PATH
# update path 
export PATH=/adaqfs/home/a-onl/bin
export PATH=/usr/local/bin:$PATH
export PATH=/adaqfs/apps/bin:$PATH
export PATH=/usr/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/sbin:$PATH
export PATH=/adaqfs/home/a-onl/bin/Linux:$PATH
export PATH=/bin:$PATH
export PATH=/usr/X11R6/bin:$PATH
export PATH=/apps/bin:$PATH
export PATH=/site/bin:$PATH
export PATH=.:$PATH
export PATH=/adaqfs/apps/contrib/bin:$PATH
export PATH=/adaqfs/apps/ROOT/pro/bin:$PATH
export PATH=$ANALYZER_PATH/bin:$PATH

echo "*** NEW PATHS ***"
echo "PATH = $PATH" 
echo "LD_LIBRARY_PATH = $LD_LIBRARY_PATH"

$ANALYZER_PATH/bin/analyzer -b -q 'get_rastersize_L.C("'$CFILE'","'$runnum'",'$FIRST','$LAST',"rastersize.root")'

RootFILE=L$runnum".root"
# spot_dir="/chafs1/work1/spot"
# new, temporary (May 19, 2021)
spot_dir=/adaq1/work1/adaq
echo "spot_dir = ${spot_dir}"
echo "pwd = $PWD"
ls -la rastersize.root
ls -la  FADC_${exp}_$runnum.pdf 

mv rastersize.root ${spot_dir}/$RootFILE
mv FADC_${exp}_$runnum.pdf ${spot_dir}/.

echo =================
echo DONE. PDFs and ROOTFILE are stored at ${spot_dir}
echo =================
echo "RUN : ${runnum}"
cd $currentdir

# evince ${spot_dir}/FADC_${exp}_$runnum.pdf &

function yes_or_no {
  while true; do
    read -p "$* [y/n]: " yn
    case $yn in
      [Yy]*) return 0 ;;
      [Nn]*) echo "No entered" ; return 1 ;;
    esac
  done
}

yes_or_no "Upload these plots to logbook HALOG? " && \
/site/ace/certified/apps/bin/logentry \
    --logbook "HALOG" \
    --tag Autolog \
    --title "Spot check using Left HRS run ${runnum}" \
    --attach ${spot_dir}/FADC_${exp}_${runnum}.pdf


